language: c
sudo: required
branches:
  except:
    - dev

services:
  - docker

before_install:
  - docker pull ocaml/opam2:alpine
  - docker run -td --name installer_builder -v $(pwd):/home/opam/oali-master ocaml/opam2:alpine
  - docker exec installer_builder sudo apk add m4
  - docker exec installer_builder opam install dune
  - docker exec installer_builder opam install core_kernel
  - docker exec installer_builder opam install fileutils
  - docker exec installer_builder opam install ppx_sexp_conv
  - docker exec installer_builder opam install re
  - docker exec installer_builder opam install sexplib
  - docker exec installer_builder opam install yojson

script:
  - docker exec installer_builder bash -c 'cd ~; echo $(pwd)'
  - docker exec installer_builder bash -c 'cd ~; ls'
  - docker exec installer_builder bash -c 'cp -r ~/oali-master ~/oali'
  - docker exec installer_builder bash -c 'chmod u=rwx ~/oali'
  - docker exec installer_builder bash -c 'eval $(opam env); cd ~/oali/; make'
  - docker cp installer_builder:/home/opam/oali/_build/default/src/oali.exe ./oali
  - strip oali

deploy:
  provider: releases
  api_key:
    secure: iSx+Ztrz9rI97R3waKGM3Lv8GehszPnjEEdY7U2wePRbOwXrdlTohoIotyGY1TbfyluzOKF51tvctpJbezRWEPUGQb173C+nv35o/fHiN6CGDT77DUzqEtFYEBlb6o4sUPtRTkKaD1qw7Jei7ttk+CDA4zRmyd/fdp/krdNdyFVYzlXklobt3+XRikRxmHioxfI9vd7AJp4VebO+4UmC9Ja7HLu7UiHtwxZOJHvpS0NFaaucN7RsgFIYQLf+pPca6M0RFSuBUS4xCA+D27/sTEjGpQicVu50uI4sMpJx2rzqf4m2OW1IERn+p2tegMofJBTxPqQERG1N1nmzbOGYKp3u9WJsV5/XmbvWrXk9LV5DbkDn7v6lkKSby905FFgqAVKxtE2VXib0rGBIJ/kHcgoz1Bvt3t6uHUMCV4R8azy400NesqpRDZc6ocKFleKEvDkYJQB5INWLUiu9rLpV2wEPjNV56EY7zULgbwlHCedKtVoHT7SCpVb6Gt4onr/GqrKKdC+0jiNWbfyKoYfNbDAonSt/mhgA4GIG/6D5/2O1hkymbtAsiOCkrPyVlh/9p8sTiWg6DxkNANkqHasn+uJPWaXKKjhSSzWuwS516uqdVdyj3xUjiyMNLeIrSvYJwbJKN4zfogsYXvHrwj7WwAqX0DV3otweCGtZt8LpWYU=
  file: oali
  on:
    tags: true
    repo: darrenldl/oali
  skip_cleanup: true

notifications:
  email:
    on_success: never
