language: c
sudo: required
branches:
  except:
    - master

services:
  - docker

before_install:
  - docker pull ocaml/opam2:alpine
  - docker run -td --name installer_builder -v $(pwd):/home/opam/installer ocaml/opam2:alpine
  - docker exec installer_builder sudo apk add m4
  - docker exec installer_builder opam install dune
  # - docker exec installer_builder opam install core_kernel
  # - docker exec installer_builder opam install fileutils
  # - docker exec installer_builder opam install ppx_sexp_conv
  # - docker exec installer_builder opam install re
  # - docker exec installer_builder opam install sexplib
  # - docker exec installer_builder bash -c 'export PATH=$PATH:~/.opam/ocaml-system/bin'
  - docker exec installer_builder bash -c 'eval $(opam env)'

script:
  - docker exec installer_builder bash -c 'cd ~; ls'
  - docker exec installer_builder bash -c 'echo $PATH'
  - docker exec installer_builder bash -c 'cd ~/installer/installer_ml; make'
